imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

build:

    dependencies:
        before:
            -
                command: "mkdir build"

checks:
    php:
        code_rating: true
        duplication: true
